name: Frontend CI

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
     - master
     - dev
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run build
    - run: npm run lint
##    - run: npm test
